services:
  next:
    build:
      context: packages/next-mono
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./packages/next-mono/data:/app/data
    
  flask:
    build:
      context: packages/flask-mono
      dockerfile: Dockerfile
    ports:
      - 5000:5000
